[package]
name = "rufetch"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
description = "Minimalistic file downloader"
readme = "README.md"
repository = "https://github.com/mattaroni/rufetch"
license = "MIT"
publish = false

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
futures-util = "0.3.32"
reqwest = { version = "0.13.4", features = ["stream"] }
tokio = { version = "1.52.3", features = ["full"] }
